name: ESP32-S3 Build ver2
permissions:
  contents: write
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Install ESP32 Core
        run: |
          arduino-cli config init

          arduino-cli config add board_manager.additional_urls \
          https://espressif.github.io/arduino-esp32/package_esp32_index.json

          arduino-cli core update-index
          arduino-cli board listall esp32:esp32s3
      - name: Install Libraries
        run: |
          arduino-cli lib update-index
      
          arduino-cli lib install "Adafruit Unified Sensor"
          arduino-cli lib install "Adafruit BME280 Library"
          arduino-cli lib install "Firebase ESP32 Client"
          arduino-cli lib install "Adafruit NeoPixel"
          arduino-cli lib install "Adafruit GFX Library"
          arduino-cli lib install "Adafruit SSD1306"
          arduino-cli lib install "DHT sensor library"
      - name: Compile
        run: |
          mkdir build

          arduino-cli compile \
            --fqbn esp32:esp32:esp32s3:FlashSize=16M,PartitionScheme=app3M_fat9M_16MB,DebugLevel=none,PSRAM=opi \
            --build-property "compiler.cpp.extra_flags=-Os" \
            --output-dir build \
            duc/duc.ino

      - name: Copy BIN
        run: |
          cp build/*.ino.bin firmware_duc.ino.bin

      - name: Commit BIN
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add firmware_duc.ino.bin
          git commit -m "update firmware bin" || echo "No changes"

          git push
